# Generated by Django 4.2.4 on 2023-08-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_product_assignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='clssification',
            new_name='classification',
        ),
    ]
