# Generated by Django 4.2.4 on 2023-08-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_rename_clssification_product_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-title'], 'permissions': (('can_add_data', 'can add a new data'),)},
        ),
    ]
